#:kivy 1.0.9

<MyWidget>:
    ceas1:

<ceas1>:
    ac: ac
    canvas:
        Rectangle:
            size: 300,300
            pos: 0,0
            source: "resources/kmh.png"
    Ac:
        id: ac
        pos: 100,100


<Ac>:
    canvas:
        Rectangle:
            size: 300,300
            pos: 0,0
            source: "resources/ac.png"
    canvas.before:
        PushMatrix
        Rotate:
            angle: self.angle
            axis: 0,0,1
            origin: self.center
    canvas.after:
        PopMatrix